# Generated by Django 4.1 on 2023-02-14 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('room_url', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('people_num', models.IntegerField(default=0)),
                ('turn', models.IntegerField(default=0)),
                ('guest', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameroom_watch', to='chat.gameroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_watch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ready', models.BooleanField(default=False)),
                ('gameroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamerooms', to='chat.gameroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
