# Generated by Django 4.1 on 2023-02-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameattend',
            name='user_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='guest',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
