# Generated by Django 4.1 on 2023-02-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameattend',
            name='user_ready',
            field=models.BooleanField(default=False),
        ),
    ]
