# Generated by Django 4.1 on 2023-05-03 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_gameattend_user_ready_gameroom_guest_gameroom_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_game', models.IntegerField(default=0)),
                ('win_game', models.IntegerField(default=0)),
                ('lose_game', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_rank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
