# Generated by Django 4.1 on 2023-05-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userrank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRank',
        ),
    ]
