# Generated by Django 4.1 on 2023-05-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_userrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='turn',
        ),
    ]
