# Generated by Django 4.1 on 2023-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_gameroom_guest_remove_gameroom_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
