# Generated by Django 4.1 on 2023-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_userrank_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='is_winning_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrank',
            name='top_winning_streak',
            field=models.IntegerField(default=0),
        ),
    ]
